### ISSUE TITLE
getResultRowForPixel not aligned with map in some cases.

### ISSUE THREAD

**Issue by jaredawebb** [omnisci/mapd-connector#169] opened 2019-11-07 21:27 UTC
I'm using the mapd-connector to build a custom layer on a mapbox map.  I use getResultRowForPixel to populate mapbox popups that display information about land parcels when they are clicked on.

Once in awhile, it seems like app gets out of sync with the rendered layer.  Upon initial load, when I click on a parcel I will get a strange address assigned to it from getResultRowForPixel that doesn't make any sense.  This occurs for every parcel I'm displaying and is persistent through zooms and map moves.  As far as I can tell no parcel has the correct address attached to it and every parcel yields a row from getResultRowForPixel when you click on it.  If I refresh and start the page from scratch, usually the problem goes away.

If the problem occurs again after refresh, or a new page load, a new wrong address will be assigned consistently to each parcels.  In other words, the wrongness is not consistent between sessions.

This occurs randomly, and sometimes I can go through maybe 20 refreshes before it shows up.  It sometimes occurs in small bursts of 2-3 refreshes before returning to normal.

For example, this is the normal behavior for a specific parcel:
![Screen Shot 2019-11-07 at 4 17 32 PM](https://user-images.githubusercontent.com/903861/68428511-5613d680-017a-11ea-9dcd-759d49d5124e.png)

And here are two failures from separate page loads.  Same parcel in each case, but different addresses being returned by getResultRowForPixel.

![Screen Shot 2019-11-07 at 4 26 45 PM](https://user-images.githubusercontent.com/903861/68429081-6f695280-017b-11ea-8689-59a95c6de525.png)

![Screen Shot 2019-11-07 at 4 18 56 PM](https://user-images.githubusercontent.com/903861/68428633-8a879280-017a-11ea-96fb-052fda75cdb1.png)

**Comment by jrajav** [comment] 2019-11-15 04:04
@jaredawebb getResultRowForPixel is dependent on having an active render session, and on getting the same widget_id as you used for the renderVega call that you're currently displaying (and using to get the x, y pixel values as input to getResultRowForPixel), in order to identify the chart. Can you please double-check that you are passing the correct widget_id each time when the issue occurs?

If you confirm that, and you're still seeing the problem, please paste an example of the getResultRowForPixel parameters and response payload, and the accompanying Vega object used to render so we can try to debug further.

**Comment by jrajav** [comment] 2019-11-15 04:55
Also, make sure your x, y pixel values are always starting from the left bottom part of the image as 0,0. If you're reading it from the usual DOM sources like offsetHeight, that means the y value usually needs to be inverted. I'm sure you figured that out, just mentioning in case that calculation could be part of the problem.

**Comment by jaredawebb** [comment] 2019-11-16 22:04
@jrajav Thanks for your help!

The parameters I'm passing to getResultRowForPixel are as follows:

`
saved_con.getResultRowForPixel(
		1,
		curr_pixel,
		{'parcels': columns},
		1,
		(err, data) => { stuff }
`
Where curr_pixel are the coordinates generated by the click on the map.  

To make sure that I am testing this consistently, I have been simulating a click on the same pixel when the map initializes, right after the connection is established and before any map movement or resizing is done.  The problem occurs maybe 1 out of 5 page loads...sometimes more frequently.

I've noticed by dumping to the console that the same pixel coordinates are associated with the same lat/lon coordinates each click.  The map overlay isn't changing at all.  getResultRowForPixel even returns the same row number each iteration, but sometimes the contents of that row changes.

For example, when the map is working correctly, the test pixel will return the following address:

<img width="829" alt="Screen Shot 2019-11-16 at 4 52 23 PM" src="https://user-images.githubusercontent.com/903861/68999672-d086d980-0891-11ea-83b7-037f1c0d3f3d.png">

However, when the error occurs row 28244 will have some other random addressed attached to it, varying from time to time:

<img width="832" alt="Screen Shot 2019-11-16 at 4 53 00 PM" src="https://user-images.githubusercontent.com/903861/68999674-eb594e00-0891-11ea-97ee-e976a55601e6.png">

<img width="855" alt="Screen Shot 2019-11-16 at 4 51 28 PM" src="https://user-images.githubusercontent.com/903861/68999678-f90ed380-0891-11ea-8280-abace8bf8498.png">

I'm also attaching the function that generates the vegaSpec.  This does not change from page load to page load, and I've verified that the same map-overlay is generated every page refresh.  The only thing that is changing is the contents of the row that getResultRowForPixel returns.

[vegaSpec.txt](https://github.com/omnisci/mapd-connector/files/3854782/vegaSpec.txt)

**Comment by vastcharade** [comment] 2019-11-18 16:50
Hi @jaredawebb. I'm wondering if you could provide a couple things to help us diagnose further:

A) what version of `omnisci_server` are you running?
B) Could you provide a server INFO log for the time period that you see the issue? A full log is preferred over a snippet.
C) Could you provide the ddl and possibly the source file for the `shape_pred_ts` table?

Providing the INFO log is the most important, particularly if you can't share the data source.

Thanks.

**Comment by randyzwitch** [comment] 2019-11-18 18:19
@vastcharade I can give you access to the server.

**Comment by jaredawebb** [comment] 2019-11-18 18:29
@vastcharade I'm happy to share the source file for the table so long as we understand that it should not be disseminated.  Do you have an email to which I can send it?

**Comment by vastcharade** [comment] 2019-11-18 20:47
Thanks @jaredawebb, at this point that's not necessary. Randy gave me access to the server, so I'm good for now.

However, I've been running some tests against your server pulling out some `render_vega` and `get_result_row_for_pixel` calls from an INFO log (specifically `omnisci_server.INFO.20191118-165135.log` lines 1-275) and I haven't been able to reproduce any issues with the getResultRowForPixel call.

I have noticed that the vega does change from time-to-time. Extracting out the render_vega calls from those lines in the log, I pulled out 3 different vegas with subtle changes between them.

Vega 1 was called once:
[flint_vega1.txt](https://github.com/omnisci/mapd-connector/files/3860453/flint_vega1.txt)

resulting in:

![flint_hittest_tests_0_a](https://user-images.githubusercontent.com/5768541/69089115-a867b980-09fc-11ea-96a3-f7bf6d3c1dd9.png)


Vega 2 was called 4 times in succession:
[flint_vega2.txt](https://github.com/omnisci/mapd-connector/files/3860455/flint_vega2.txt)

![flint_hittest_tests_1_a](https://user-images.githubusercontent.com/5768541/69089145-af8ec780-09fc-11ea-8760-6d7e75543342.png)


Vega 3 was called 3 times in succession: 
[flint_vega3.txt](https://github.com/omnisci/mapd-connector/files/3860456/flint_vega3.txt)

![flint_hittest_tests_5_a](https://user-images.githubusercontent.com/5768541/69089154-b289b800-09fc-11ea-85ab-5ef693314808.png)


When running `getResultRowForPixel` with a pixel radius of 1 after each of those renders gives me this:

vega 1: hits "902 STOCKDALE ST"
vega 2: hits "1629 ILLINOIS AVE" all 4 times
vega 3: no result, all 3 times.

the return is not changing under the hood for me from just picking up those 8 renders/hit-tests. Everything seems to be working as expected. If you look closer at the renders, you do see that there's nothing rendered at pixel 558,636 for that last vega.

and if I put an additional filter into the sql for the first 2 vegas for "902 STOCKDALE ST" and "1629 ILLINOIS AVE" respectively, there is something rendered at that pixel location 558,636 (from lower lefthand corner).

So it all seems to be behaving correctly from what I've cherry-picked from the logs. That's not to say there isn't a bug, but i just want to be sure you're not getting tripped up by your application producing subtle changes in the vega (namely width/height and map bounds, which would surely change the result of `getResultRowForPixel`).

I think the best way forward is either you point me to a log snippet from times where there is weird behavior so I know I'm looking at the right place.

**Comment by jaredawebb** [comment] 2019-11-18 20:59
@vastcharade I just refreshed the application 8 times (around 3:50 pm EST) and had two failure at pixel 502, 635.  Six clicks (correctly) returned "810 WILBERFORCE DR."  The last error returned "2902 PLAINFIELD AVE."

The test click happens at the same pixel each refresh as soon as the webpage loads, so there is no map resizing or shifting happening.  I've been downloading the overlay at each refresh as well and the images are identical to each other.

**Comment by vastcharade** [comment] 2019-11-18 22:21
I'm able to reproduce now @jaredawebb, thanks. It's now obvious something is wrong with poly cache hittesting. This should work, but do note that poly cache rendering is being deprecated. If you have no preference between cached/non-cached poly rendering, I suggest you switch to the non-cached version. You will be in a better place moving forward.

To do so, all you need to do is add the `omnisci_geo` column to the sql in the vegas. 

In the non-cached version it'd also be preferred that you filter out the polygons to only those visible in the view. For instance, here's a vega from the log you pointed me to:

```
{
  "width": 829,
  "height": 1158,
  "data": [
    {
      "name": "parcels_hist",
      "format": "polys",
      "sql": "SELECT                   rowid,                   PropertyAd,                   sl_private,                   sl_public_,                   replaced,                   dangerous as danger_level,                  avg_,                  created_at                FROM                   shape_pred_ts                WHERE                 UseType = 'Residential' AND created_at < '2019-05-01'"
    },
    {
      "name": "parcels",
      "format": "polys",
      "sql": "SELECT                   rowid,                   PropertyAd,                   sl_private,                   sl_public_,                   replaced,                   curr_dange as danger_level,                  avg_,                  created_at                FROM                   shape_pred_ts                WHERE                 UseType = 'Residential'"
    }
  ],
  "scales": [
    {
      "name": "fill_color",
      "type": "ordinal",
      "domain": [
        0,
        1,
        2,
        3,
        4,
        5
      ],
      "range": [
        "rgb(0, 128, 0)",
        "rgb(173,255,47)",
        "rgb(255,255,0)",
        "rgb(255,80,0)",
        "rgb(255,0 , 0)",
        "rgb(220,220,220)"
      ]
    },
    {
      "name": "fill_color_expert",
      "type": "ordinal",
      "domain": [
        0,
        1
      ],
      "range": [
        "rgb(0, 128, 0)",
        "rgb(255,0 , 0)"
      ]
    },
    {
      "name": "fill_color_colorblind",
      "type": "ordinal",
      "domain": [
        0,
        1,
        2,
        3,
        4,
        5
      ],
      "range": [
        "rgb(140,81,10)",
        "rgb(216,179,101)",
        "rgb(199,234,229)",
        "rgb(90,180,172)",
        "rgb(1,102,94)",
        "rgb(220, 220, 220)"
      ]
    }
  ],
  "projections": [
    {
      "name": "merc",
      "type": "mercator",
      "bounds": {
        "x": [
          -83.77008999132805,
          -83.63568200869204
        ],
        "y": [
          42.9561099999859,
          43.09336599998986
        ]
      }
    }
  ],
  "marks": [
    {
      "type": "polys",
      "from": {
        "data": "parcels"
      },
      "properties": {
        "x": {
          "field": "x"
        },
        "y": {
          "field": "y"
        },
        "fillColor": {
          "scale": "fill_color",
          "field": "danger_level"
        },
        "strokeColor": "rgb(0,0,0)",
        "strokeWidth": 0,
        "lineJoin": "bevel"
      },
      "transform": {
        "projection": "merc"
      }
    }
  ]
}
```

For non-cached (in-situ) poly rendering, the queries would look like this:

`SELECT omnisci_geo, rowid, PropertyAd, sl_private, sl_public_, replaced, dangerous as danger_level, avg_, created_at FROM shape_pred_ts WHERE (ST_XMax(omnisci_geo) >= -83.77008999132805 AND ST_XMin(omnisci_geo) <= -83.63568200869204 AND ST_YMax(omnisci_geo) >= 42.9561099999859 AND ST_YMin(omnisci_geo) <= 43.09336599998986) AND UseType = 'Residential' AND created_at < '2019-05-01'`

and 

`SELECT omnisci_geo, rowid, PropertyAd, sl_private, sl_public_, replaced, curr_dange as danger_level, avg_, created_at FROM shape_pred_ts WHERE (ST_XMax(omnisci_geo) >= -83.77008999132805 AND ST_XMin(omnisci_geo) <= -83.63568200869204 AND ST_YMax(omnisci_geo) >= 42.9561099999859 AND ST_YMin(omnisci_geo) <= 43.09336599998986) AND UseType = 'Residential'`

respectively.

Notice that the new WHERE filter uses the same bounds values as that defined in the "merc" projection.

And after looking at your vegas more closely, I have some suggestions for you for a more optimized render (either cached or non-cached):

1) It looks like the `parcels_hist` vega data table is never used. Perhaps you intend to swap between the `parcels` and `parcels_hist` tables at some point, but at present both queries get executed even tho you only render from `parcels`. This will be addressed in a future version, but until then be aware that you are executing two queries here even tho you only use the results from one.

2) you don't need all those additional columns in the query. They end up taking more time and space to process. The only things you need in the query are those that are directly referenced in the vega. You can still query for additional columns via `getResultRowForPixel` as long as the query is a projection query (which it is in this case).

Given that, the `parcel` query becomes (for a non-poly cached query):

`SELECT omnisci_geo, rowid, curr_dange as danger_level FROM shape_pred_ts WHERE (ST_XMax(omnisci_geo) >= -83.77008999132805 AND ST_XMin(omnisci_geo) <= -83.63568200869204 AND ST_YMax(omnisci_geo) >= 42.9561099999859 AND ST_YMin(omnisci_geo) <= 43.09336599998986) AND UseType = 'Residential'`

Such optimizations should improve your rendering performance and memory footprint.

**Comment by vastcharade** [comment] 2019-11-18 22:23
And it seems everything works correctly if you use the non-cached poly rendering, FYI.

**Comment by jaredawebb** [comment] 2019-11-19 03:45
@vastcharade Thank you so much for your careful attention.  You definitely went above and beyond what was necessary here.  I haven't seen the bug turn up since I made the change AND it improved performance (along with implementing your other suggestions).

**Closed** 2019-11-19 04:29 UTC

**Comment by vastcharade** [comment] 2019-11-19 23:11
FYI, I did find the source of the bug with the poly cache, and the fix will be in the next release. Probably irrelevant now since it sounds like you're going the other route.
